### ISSUE TITLE
themes are looked for in /node_modules/ghost/content/themes/ rather than /content/themes/

### ISSUE THREAD

**Issue by simonv3** [mozz100/ghost-on-webfaction#1] opened 2015-08-24 02:30 UTC
Is that a config problem?

(Thanks for this script, I haven't tried upgrading yet because it's at the most recent version of ghost, but the promise is great!)

**Comment by mozz100** [comment] 2015-08-24 10:15
Ah, I see what you mean.  Yes, config, I think. For me, this fixed it: include the `contentPath` in your `config.js`, even though it seems redundant. Ghost then looks in your `content/themes` directory rather than the one inside `node_modules`.  I've committed this to the example (see commit link below), you should be able to copy and paste, or reinstall if you haven't got too far in.

https://github.com/mozz100/ghost-on-webfaction/commit/2970a09f55d019693756542b37db45716f6adc8e

**Comment by mozz100** [comment] 2015-08-24 10:15
P.S. thanks for the catch - and the suggestion of what might be the cause. It's appreciated.  Let me know how you're getting on

**Closed as completed by mozz100** 2015-08-24 10:15 UTC

**Comment by simonv3** [comment] 2015-08-24 18:44
Awesome, thanks, this worked great. Makes sense to fiddle with ghost config variables.
